#!/usr/bin/python3
# SPDX-License-Identifier: MIT
# (c) Hanno Böck
#
# Fuzzing [badkeys](https://badkeys.info) with [python-afl](https://github.com/jwilk/python-afl)
#
# Usage:
#   py-afl-fuzz -i keys -o out ./fuzzdkim

import sys

import afl

from badkeys.dkim import parsedkim

afl.init()

parsedkim(sys.stdin.read())
