#!/usr/bin/python3
# SPDX-License-Identifier: MIT
# (c) Hanno Böck
#
# Fuzzing [badkeys](https://badkeys.info) with [python-afl](https://github.com/jwilk/python-afl)
#
# Usage example:
#   py-afl-fuzz -i keys -o out ./fuzzbk.py

import sys

import afl

import badkeys

afl.init()

badkeys.detectandcheck(sys.stdin.read())
