name: runci
on:
- pull_request
- push

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8,3.x]
        os: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pycodestyle pyflakes dlint pyupgrade black
      - name: Run tests
        shell: bash
        run: |
          ./runci.sh
