---
name: runci
"on":
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          # gmpy2 needs mpfr headers to build
          sudo apt-get -y install libmpfr-dev libmpc-dev
          python -m pip install --upgrade pip

          # force gmpy2 alpha for python 3.12 support,
          # please remove later
          pip install 'gmpy2>=2.2.0a1'

          pip install -r requirements.txt
          pip install pycodestyle pyflakes dlint pyupgrade black
      - name: Run tests
        shell: bash
        run: |
          ./runci.sh
